name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: git clone git@github.com:realtimeprojects/acre.git
      
    - name: Run check
      run: acre/bin/acre
      
    - name: Run distcheck
      run: make distcheck
