name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      uses: actions/checkout@v2
      with:
        repository: realtimeprojects/acre
        ref: master

    - name: Run check
      run: acre/bin/acre
      
    - name: Run distcheck
      run: make distcheck
